FORMAT: 1A
HOST: http://api.devshop.dev/

# devshopAPI

API responsavél por efetuar operações para comércio eletrônico de desenvolvedores.

## Coleção de Desenvolvedores [/developers?q=faelribeiro22&page=1&language=javascript&company=vitta]

### Lista todos os desenvolvedores que possuem os filtros [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Rafael Ribeiro de Sousa",
                "company": "Vitta",
                "value": 22.3,
                "picture": "https://avatars1.githubusercontent.com/u/10289821?v=4",
                "languages": ["javascript", "C", "java", "html"]
            },
            "page": 1,
            "currentPage": 1,
            "nextPage": 2,
            "previousPage": 0
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }